[project]
name = "semantic-dataset-search"
version = "0.1.0"
description = "A solution to perform semantic search on dataset catalogues"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb==1.0.9",
    "elastic-transport==8.17.1",
    "elasticsearch==9.0.1",
    "fastapi==0.115.9",
    "httpx==0.28.1",
    "langchain-core==0.3.49",
    "langchain-groq==0.3.0",
    "langchain-ollama==0.3.0",
    "numpy==2.2.4",
    "pandas==2.2.3",
    "pydantic==2.11.1",
    "python-dotenv==1.1.0",
    "ruff>=0.14.1",
    "sentence-transformers==4.1.0",
    "starlette==0.45.3",
    "typing-extensions==4.12.2",
    "uvicorn==0.34.2",
]
